add header, first section
yuschenko-maria/WD pull request #2
Opened 2022-07-25 00:01 UTC by yuschenko-maria

2022-07-25 19:11 UTC, conho-web commented on css/style.css
> +  }
Shift + Alt + F (это сочетание клавиш автоматически выровняет красиво код, если ты пишешь в vs code)

2022-07-26 11:40 UTC, conho-web reviewed
Решил немножечко помочь)

2022-07-26 11:40 UTC, conho-web commented on css/style.css
> +    width: 34,5rem;
Тут точечку надо поставить

2022-07-26 11:40 UTC, conho-web commented on css/style.css
> +    height: fit-content;
https://developer.mozilla.org/en-US/docs/Web/CSS/fit-content
Почитай про эту штуку, вряд ли она здесь нужна

2022-07-26 11:40 UTC, conho-web commented on css/style.css
> +@media (max-width:1350px) {
<img width="155" alt="Снимок экрана 2022-07-26 в 14 20 49" src="https://user-images.githubusercontent.com/98264524/180994242-f4092c94-a7dd-433a-bab1-20b0de464c1f.png">
Можешь убрать все медиа запросы, и вместо максимальной ширину контейнеру задать просто padding по бокам
Результат будет лучше, и кода намного меньше

2022-07-26 11:40 UTC, conho-web commented on css/style.css
> +    font-size: 16px;
Эту строку можно убрать, потому что по умолчанию шрифт стоит 16px

2022-07-26 11:40 UTC, conho-web commented on css/style.css
> +    left: 1023px;
top, left, right, bottom у тебя не будут работать, потому что эти штуку используются при абсолютном позиционировании
https://www.youtube.com/watch?v=mpykT40_VBc (вот видосик на эту тему)

2022-07-26 11:40 UTC, conho-web commented on css/style.css
> +    border-radius: 0px;
border-radius отвечает за закругление углов, а у тебя по умолчанию у блока нет закруглений, поэтому нет смысла обнулять эту штучку

2022-07-26 11:40 UTC, conho-web commented on index.html
> +                    <h1 class="main_title">Квартирные<br>переезды</h1>
Текст лучше не переносить так на новую строку, а ставить max-width

2022-07-26 11:40 UTC, conho-web commented on index.html
> +                        <span class="button_shadow"></span>
Если не разобралась с тенью для кнопочки, то можешь глянуть как я делал
https://conho-web.github.io/stage-1/

Если что-то будет не понятно, то могу объяснить (discord: conho#5324)

2022-07-26 11:40 UTC, conho-web commented on css/style.css
> +    font-weight: 400;
font-weight: 400 (толщина regular)
Она стоит по умолчанию, поэтому нет смысла прописывать эту штучку

2022-07-26 11:40 UTC, conho-web commented on css/style.css
> +    height: 629px;
Давать высоту блоку (особенно в фиксированной величине) не является хорошей практикой
На сколько я понял, ты так избавлялась от маленького отступа снизу картинки
Вместо фиксированной высоты я предложил бы картинке height: 100% задать, и тогда она плотно ляжет

2022-07-26 11:40 UTC, conho-web commented on css/style.css
> +    letter-spacing: 0em;
letter-spacing по умолчанию ноль стоит
От этой строчки тоже смысла нет

2022-07-26 11:40 UTC, conho-web commented on css/style.css
> +a{
Лучше добавить класс этой штуке, потому что потом на странице у тебя могут быть еще возможно ссылки с другими стилями, и столкнешься с проблемой

2022-08-08 12:36 UTC, conho-web commented on css/style.css
> +        margin: 0 5px ;
Я бы ставил здесь margin: 0 auto, чтобы контэйнер стал по центру

2022-08-08 12:36 UTC, conho-web commented on css/style.css
> +@media screen and (max-width:1200px) {
Я бы не делал мобилку на 1200px, а уменьшил бы здесь еще десктоп

2022-08-08 12:36 UTC, conho-web commented on css/style.css
> +    height: 2.6rem;
Зря задаешь высоту этому блоку, она здесь вроде как и не нужна

2022-08-08 12:36 UTC, conho-web commented on css/style.css
> +.main__pic{
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/98264524/183413287-a9a7c333-dacd-4a3a-bb3a-e1b8e77c05cd.png">
На этом разрешении мобилка выходит за пределы контейнера
Здесь будет лучше созвониться и показать что можно было бы изменить, чтобы картинка больше жила
Напиши, как будешь свободна, и созвонимся

2022-08-08 12:36 UTC, conho-web commented on css/style.css
> +button{
Лучше обращаться по классу, потому что это у тебя еще будут кнопки на странице, и запутаешься потом разбираться с этими стилями, которые будут присваиваться каждой кнопке

2022-08-08 12:36 UTC, conho-web commented on css/style.css
> +.main__title{
Если не ошибаюсь, то по БЭМ у тебя ошибка с названием класса
Тут должен быть welcome__title, и так далее
То есть все дальнейшие штуки идут от одного блока

2022-08-08 12:36 UTC, conho-web commented on css/style.css
> +    height: 3.75rem;
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/98264524/183416456-e6ec9c69-4231-441d-b448-e0538ff76bc3.png">
Вот почему не стоит задавать фиксированные значения даже кнопкам
Потому что туда могут добавить текст, и кнопка уже будет выглядеть не очень
Поэтому лучше делать кнопку паддингом

2022-08-08 12:36 UTC, conho-web commented on css/style.css
> +    width: 34rem;
Мы как-то с Артемом тебе говорили о том, что фиксированная ширина - не лучшая затея)
Одна из причин проблем с картинкой как раз так и был этот момент))
Подробнее на созвоне)))

2022-08-08 12:36 UTC, conho-web commented on css/style.css
> +        padding-left: 15px;
Это что-то похожее на костыль
Если задашь header__container margin 0 auto, как я писал в одно из комментов, то тебе этот паддинг уже и не нужен)

2022-08-08 12:36 UTC, conho-web commented on css/style.css
> +    .order__button{
Этой кнопке не хватает отступа снизу, как должен быть на макете

2022-08-08 16:58 UTC, conho-web commented on css/style.css
> -    width: 34rem;
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/98264524/183469814-f50c2a4c-29af-4f7f-97da-b5953ea367c2.png">
Все бы хорошо, но у них между собой нет отступа, и это выглядит не очень

2022-08-08 16:58 UTC, conho-web commented on css/style.css
> +.welcome__pic{
<img width="302" alt="Screenshot 2022-08-08 at 19 46 06" src="https://user-images.githubusercontent.com/98264524/183470157-86c6772b-a937-46b4-83b5-1ace31829c97.png">
У тебя отступ маленький между картинкой и блоком есть
Чтобы его убрать я задал блоку height auto, а картинке height 100%

2022-08-08 16:58 UTC, conho-web commented on css/style.css
> +.welcome__title{
<img width="601" alt="Screenshot 2022-08-08 at 19 47 23" src="https://user-images.githubusercontent.com/98264524/183470428-738dfe9c-0d77-483c-92a3-ae70c0a04a7b.png">
Примерно в диапазоне между 1200 и 1180 пикселей у тебя картинка выглядит так (не очень, как по мне)
Я бы поэтому задал максимальную ширину заголовку

2022-08-08 16:58 UTC, conho-web commented on css/style.css
>      font-size: 4.3rem;
<img width="547" alt="Screenshot 2022-08-08 at 19 50 30" src="https://user-images.githubusercontent.com/98264524/183471111-8982200c-2c5e-4ef0-99e5-6a78ecc84847.png">
Еще прикол с line-height, он у тебя слишком большой
И почти незаметен отступ от кнопки

2022-08-08 16:58 UTC, conho-web commented on css/style.css
> +@media screen and (max-width:960px){
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/98264524/183471620-e78f422c-303c-4c23-ba80-113d4827d6f6.png">
Пару пикселей до 960 у тебя картинка не совсем выглядит
Дизайнеры бы не одобрили)

2022-08-08 16:58 UTC, conho-web commented on css/style.css
> +@media screen and (max-width:768px) {
<img width="557" alt="Screenshot 2022-08-08 at 19 53 46" src="https://user-images.githubusercontent.com/98264524/183471897-ce87277f-0d13-40f5-af05-65fefdc566d3.png">
И тут до 768 еще есть промежутки, за которые тебя дизайнер явно расстрелял бы)

2022-08-08 16:58 UTC, conho-web commented on css/style.css
>      .container{
<img width="557" alt="Screenshot 2022-08-08 at 19 53 46" src="https://user-images.githubusercontent.com/98264524/183472335-f8759122-f1c6-4d79-b32e-4d61b15c9c5f.png">
Здесь у тебя чуть картинка за кнопку вылазит
Я бы сделал кнопку на всю ширину контейнера, как по макету
Плюс немного картинка на заголовки налазит

2022-08-08 19:17 UTC, i-barysiuk commented on css/style.css
> +a{
Эту штуку так или иначе надо учится правильно называть) А называется она правильно тег а

2022-08-15 11:56 UTC, i-barysiuk requested changes

2022-08-15 11:56 UTC, i-barysiuk commented on index.html
> +            <a href="tel:8(029)-999-13-12" class="header__number">8(029)-999-13-12</a>
Я как пользователь не могу нажать на номер телефона. Его заслоняет фотография мужичка

2022-08-15 11:56 UTC, i-barysiuk commented on index.html
> +                                <img src="assets/png/truck.png" alt="truck">
Советую заменить иконки на SVG они будут меньше весить и сильно лучше показываться на экране

2022-08-15 11:56 UTC, i-barysiuk commented on index.html
> +                    <h1 class="welcome__title">Квартирные переезды</h1>
Внимательно проверь цвет текста. Он везде должен быть серый а у тебя в заголовке и тексте местами все еще черный

2022-08-15 13:01 UTC, i-barysiuk approved these changes

2022-08-15 13:04 UTC, merged